function out = corr_err(corr_func,corr_opts,counts) 
est_fun = @(c,a,opts) corr_wrap(corr_func,c,a,opts);
out=bootstrap_se(est_fun,counts,...
    'samp_frac_lims',[0.1,0.5],...
    'num_samp_frac',10,...
    'num_samp_rep',1e2,...
    'use_frac_size',true,...
    'opp_arguments',{corr_opts},...
    'verbose',0);
end

function corr_density = corr_wrap(corr_func,counts,atten,corr_opts)
corr_opts.attenuate_counts = atten;
corr_opts.plots = false;
corr_opts.print_update = false;
out = corr_func(corr_opts,counts);
corr_density = out.one_d_corr_density_raw;
end